//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Article.
        /// </summary>
        internal static string DefaultArticleName {
            get {
                return ResourceManager.GetString("DefaultArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given moniker could be attributed to an object to load..
        /// </summary>
        internal static string InvalidMonikerExceptionDefault {
            get {
                return ResourceManager.GetString("InvalidMonikerExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moniker, {0}, is not valid for a {1} factory..
        /// </summary>
        internal static string InvalidMonikerExceptionFromMonikerAndFactory {
            get {
                return ResourceManager.GetString("InvalidMonikerExceptionFromMonikerAndFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of retries allowed has been exceeded.  Impossible to connect..
        /// </summary>
        internal static string RetryExhaustedExceptionDefault {
            get {
                return ResourceManager.GetString("RetryExhaustedExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to connect {0} times.  All failed.  Giving up..
        /// </summary>
        internal static string RetryExhaustedExceptionFromFailures {
            get {
                return ResourceManager.GetString("RetryExhaustedExceptionFromFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided wiki was not created by a {0} factory.  .
        /// </summary>
        internal static string WikiFactoryBaseCloseWikiNotMine {
            get {
                return ResourceManager.GetString("WikiFactoryBaseCloseWikiNotMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given wiki was not found..
        /// </summary>
        internal static string WikiNotFoundExceptionDefault {
            get {
                return ResourceManager.GetString("WikiNotFoundExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given wiki, {0}, was not found..
        /// </summary>
        internal static string WikiNotFoundExceptionMoniker {
            get {
                return ResourceManager.GetString("WikiNotFoundExceptionMoniker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wiki could not be closed..
        /// </summary>
        internal static string WikiUnclosedExceptionDefault {
            get {
                return ResourceManager.GetString("WikiUnclosedExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wiki, {0} could not be closed by (1) factory..
        /// </summary>
        internal static string WikiUnclosedExceptionFromMonikerAndFactory {
            get {
                return ResourceManager.GetString("WikiUnclosedExceptionFromMonikerAndFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wiki could not be opened..
        /// </summary>
        internal static string WikiUnopenedExceptionDefault {
            get {
                return ResourceManager.GetString("WikiUnopenedExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wiki, {0} could not be opened by {1} factory..
        /// </summary>
        internal static string WikiUnopenedExceptionFromMonikerAndFactory {
            get {
                return ResourceManager.GetString("WikiUnopenedExceptionFromMonikerAndFactory", resourceCulture);
            }
        }
    }
}
